# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#bbrda
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Gym.create brand: "Pure Fitness", branch: "IFC Mall", territory: "Hong Kong", district: "Central", address: "3/F IFC Mall, 8 Finance Street", telephone: "8129 8000", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1500, membership_short: 1000, membership_long: 840
Gym.create brand: "Pure Fitness", branch: "Kinwick Centre", territory: "Hong Kong", district: "Soho", address: "3/F Kinwick Centre, 32 Hollywood Road", telephone: "2180 8088", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: false, steam: false, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1500, membership_short: 1000, membership_long: 840
Gym.create brand: "Pure Fitness", branch: "Fairmont House", territory: "Hong Kong", district: "Admiralty", address: "Levels 1 & 2, Fairmont House, 8 Cotton Tree Drive", telephone: "8129 2228", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: true, pt: true, spinning: true, sauna: false, steam: false, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: true, membership_monthly: 1500, membership_short: 1000, membership_long: 840
Gym.create brand: "Pure Fitness", branch: "Lee Theatre Plaza", territory: "Hong Kong", district: "Causeway Bay", address: "15/F Lee Theatre Plaza, 99 Percival Street", telephone: "8196 0000", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: true, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: true, membership_monthly: 1500, membership_short: 1000, membership_long: 840
Gym.create brand: "Pure Fitness", branch: "The Pulse", territory: "Hong Kong", district: "Repulse Bay", address: "Shop 110, The Pulse, 28 Beach Road", telephone: false, cardio: false, crossfit: false, free_weights: false, group_studios: false, machine_weights: false, mma: false, lounge: false, pt: false, spinning: false, sauna: false, steam: false, spa: false, pool: false, yoga: false, yoga_hot: false, wifi: false, clothes: false, juice_bar: false, membership_monthly: 1500, membership_short: 1000, membership_long: 840
Gym.create brand: "Pure Fitness", branch: "Langham Place Office Tower", territory: "Kowloon", district: "Mongkok", address: "7/F, Langham Place Office Tower, 8 Argyle Street", telephone: "8129 2828", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1500, membership_short: 1000, membership_long: 840

Gym.create brand: "Fitness First", branch: "Exchange Square", territory: "Hong Kong", district: "Central", address: "37/F, One Exchange Square", telephone: "2525 2900", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "Hopewell Centre", territory: "Hong Kong", district: "Wan Chai", address: "16/F, Hopewell Centre, 183 Queen’s Road East", telephone: "3106 3878", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: false, steam: true, spa: false, pool: false, yoga: true, yoga_hot: true, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "Olympia Plaza", territory: "Hong Kong", district: "North Point", address: "4/F, Olympia Plaza, 255 King’s Road", telephone: "3106 3222", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "Taikoo Place", territory: "Kowloon", district: "Quarry Bay", address: "4/F, PCCW Tower, Taikoo Place", telephone: "3106 3333", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: true, steam: true, spa: true, pool: false, yoga: false, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "One Pacific Centre", territory: "Kowloon", district: "Kwun Tong", address: "25/F, One Pacific Centre, 414 Kwun Tong Road", telephone: "3106 3538", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: false, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "Harbour City", territory: "Kowloon", district: "Tsim Sha Tsui", address: "5/F, World Commerce Centre, 11 Canton Road", telephone: "3106 3111", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: false, steam: false, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999
Gym.create brand: "Fitness First", branch: "Sheraton", territory: "Kowloon", district: "Tsim Sha Tsui", address: "18/F, Sheraton Hotel, 20 Nathan Road", telephone: "2732 6801", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: false, pt: true, spinning: false, sauna: true, steam: false, spa: true, pool: true, yoga: true, yoga_hot: false, wifi: true, clothes: true, juice_bar: false, membership_monthly: 1800, membership_short: 1150, membership_long: 999


Gym.create brand: "California Fitness", branch: "The L Place", territory: "Hong Kong", district: "Central", address: "6/F, the L Place, 139 Queen's Road", telephone: "2522 5229", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: false, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Elizabeth House", territory: "Hong Kong", district: "Causeway Bay", address: "4/F, Elizabeth House, 250 Gloucester Road", telephone: "2577 0004", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: false, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Kin Lee Building", territory: "Hong Kong", district: "Wan Chai", address: "G/F, Kin Lee Building, 9-13 O'Brien Road", telephone: "2877 7070", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: false, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Parkvale", territory: "Hong Kong", district: "Quarry Bay", address: "Parkvale, 1060 King's Road", telephone: "2880 9660", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: false, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "The ONE", territory: "Kowloon", district: "Tsim Sha Tsui", address: "9/F, The ONE, 100 Nathan Road", telephone: "2366 8666", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: true, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Grand Plaza", territory: "Kowloon", district: "Mongkok", address: "5/F, Grand Plaza, 639 Nathan Road", telephone: "2522 1000", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: true, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Megabox", territory: "Kowloon", district: "Kowloon Bay", address: "18/F, MegaBox, 38 Wang Chiu Road", telephone: "2250 5022", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: true, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: true, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Whampoa", territory: "Kowloon", district: "Hunghom", address: "G/F, Treasure World (Site 11), Whampoa Garden", telephone: "2622 2228", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: true, lounge: false, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: true, membership_monthly: 1599, membership_short: 1099, membership_long: 901
Gym.create brand: "California Fitness", branch: "Tuen Mun Centre", territory: "Kowloon", district: "Tuen Mun", address: "Tuen Mun Centre, 7-35 Yan Ching Street", telephone: "2618 3008", cardio: false, crossfit: false, free_weights: false, group_studios: false, machine_weights: false, mma: false, lounge: false, pt: false, spinning: false, sauna: false, steam: false, spa: false, pool: false, yoga: false, yoga_hot: false, wifi: false, clothes: false, juice_bar: false, membership_monthly: 1599, membership_short: 1099, membership_long: 901


Gym.create brand: "Physical Fitness", branch: "Concord Square", territory: "New Territories", district: "Tsuen Wan", address: "2-3/F, Concord Square, 88 Chuen Lung Street", telephone: "3710 7777", cardio: true, crossfit: false, free_weights: true, group_studios: true, machine_weights: true, mma: false, lounge: true, pt: true, spinning: true, sauna: true, steam: true, spa: false, pool: false, yoga: true, yoga_hot: false, wifi: true, clothes: false, juice_bar: false, membership_monthly: 1111, membership_short: 888, membership_long: 666



